
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.Date;
import java.util.Random;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mavi
 */
public class PencereOyun extends javax.swing.JFrame {

    /**
     * Creates new form PencereOyun
     */
    public PencereOyun() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSoru = new javax.swing.JPanel();
        lblKelime = new javax.swing.JLabel();
        lblSoru = new javax.swing.JLabel();
        pnlTahminEt = new javax.swing.JPanel();
        textFieldTahminKelime = new javax.swing.JTextField();
        lblTahminKelimeGoster = new javax.swing.JLabel();
        btnGonder = new javax.swing.JButton();
        btnSil = new javax.swing.JButton();
        btnHarfiste = new javax.swing.JButton();
        btnOyunuBitir = new javax.swing.JButton();
        pnlSurePuan = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblToplamPuan = new javax.swing.JLabel();
        pnlSoruPuan = new javax.swing.JPanel();
        lblSoruPuan = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlSoru.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("SORU"), "SORU"));

        lblKelime.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblKelime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKelime.setText("KELİME");

        lblSoru.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSoru.setText("SORU");

        javax.swing.GroupLayout pnlSoruLayout = new javax.swing.GroupLayout(pnlSoru);
        pnlSoru.setLayout(pnlSoruLayout);
        pnlSoruLayout.setHorizontalGroup(
            pnlSoruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSoruLayout.createSequentialGroup()
                .addGroup(pnlSoruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSoruLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(lblKelime, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSoruLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSoru, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnlSoruLayout.setVerticalGroup(
            pnlSoruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSoruLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKelime, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(lblSoru, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlTahminEt.setBorder(javax.swing.BorderFactory.createTitledBorder("TAHMİN ET"));

        textFieldTahminKelime.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        textFieldTahminKelime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldTahminKelimeActionPerformed(evt);
            }
        });
        textFieldTahminKelime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFieldTahminKelimeKeyPressed(evt);
            }
        });

        lblTahminKelimeGoster.setText("gönderilen kelime burada yazacak");

        btnGonder.setText("GÖNDER");
        btnGonder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGonderActionPerformed(evt);
            }
        });

        btnSil.setText("SİL");
        btnSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSilActionPerformed(evt);
            }
        });

        btnHarfiste.setText("HARF iSTE");
        btnHarfiste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHarfisteActionPerformed(evt);
            }
        });

        btnOyunuBitir.setText("OYUNU SONLANDIR");
        btnOyunuBitir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOyunuBitirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTahminEtLayout = new javax.swing.GroupLayout(pnlTahminEt);
        pnlTahminEt.setLayout(pnlTahminEtLayout);
        pnlTahminEtLayout.setHorizontalGroup(
            pnlTahminEtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTahminEtLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlTahminEtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTahminKelimeGoster, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldTahminKelime, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOyunuBitir, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(pnlTahminEtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTahminEtLayout.createSequentialGroup()
                        .addComponent(btnHarfiste, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTahminEtLayout.createSequentialGroup()
                        .addGroup(pnlTahminEtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnSil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGonder, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                        .addGap(21, 21, 21))))
        );
        pnlTahminEtLayout.setVerticalGroup(
            pnlTahminEtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTahminEtLayout.createSequentialGroup()
                .addGroup(pnlTahminEtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textFieldTahminKelime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHarfiste, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(pnlTahminEtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGonder, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTahminKelimeGoster, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTahminEtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTahminEtLayout.createSequentialGroup()
                        .addComponent(btnSil, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTahminEtLayout.createSequentialGroup()
                        .addComponent(btnOyunuBitir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))))
        );

        pnlSurePuan.setBorder(javax.swing.BorderFactory.createTitledBorder("SÜRE/PUAN"));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("TOPLAM PUAN"));

        lblToplamPuan.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblToplamPuan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblToplamPuan.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblToplamPuan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblToplamPuan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSoruPuan.setBorder(javax.swing.BorderFactory.createTitledBorder("SORU PUAN DEĞERİ"));

        lblSoruPuan.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblSoruPuan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSoruPuan.setText("0");

        javax.swing.GroupLayout pnlSoruPuanLayout = new javax.swing.GroupLayout(pnlSoruPuan);
        pnlSoruPuan.setLayout(pnlSoruPuanLayout);
        pnlSoruPuanLayout.setHorizontalGroup(
            pnlSoruPuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSoruPuan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        pnlSoruPuanLayout.setVerticalGroup(
            pnlSoruPuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSoruPuanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSoruPuan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("SÜRE"));

        lblTime.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTime.setText("0");
        lblTime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblTimeKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlSurePuanLayout = new javax.swing.GroupLayout(pnlSurePuan);
        pnlSurePuan.setLayout(pnlSurePuanLayout);
        pnlSurePuanLayout.setHorizontalGroup(
            pnlSurePuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSurePuanLayout.createSequentialGroup()
                .addGroup(pnlSurePuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSurePuanLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(pnlSoruPuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSurePuanLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        pnlSurePuanLayout.setVerticalGroup(
            pnlSurePuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSurePuanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSurePuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSoruPuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlSoru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnlTahminEt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlSurePuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pnlSoru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlSurePuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTahminEt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldTahminKelimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldTahminKelimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldTahminKelimeActionPerformed
    int toplamPuan=0;
    private void btnGonderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGonderActionPerformed
       String tahminKelime;
       tahminKelime = textFieldTahminKelime.getText();//textField içerisine yazılan string kelimeyi al ve string bir değişkene ata
       String tahminKelime1=tahminKelime.toUpperCase();
       lblTahminKelimeGoster.setText(tahminKelime1);
       
        if (tahminKelime1.equals(diziKelime[tut])) 
        {
            toplamPuan+=puan;
        }
        else
            toplamPuan-=puan;
        ekranaYaz();
        lblToplamPuan.setText(Integer.toString(toplamPuan));
        
        
    }//GEN-LAST:event_btnGonderActionPerformed

    private void btnSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSilActionPerformed
        textFieldTahminKelime.setText("");//textField içerisini boş yap
    }//GEN-LAST:event_btnSilActionPerformed
    char [] ekranYaz1=null;
    
    private void btnHarfisteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHarfisteActionPerformed
        Random harfCek=new Random();
        int index;
        do {
            index=harfCek.nextInt(harf.length);
            
        } while (harf[index]=='*');
        
        ekranYaz1[index]=harf[index];
        harf[index]='*';
        lblKelime.setText("");
        
        for (int i = 0; i < ekranYaz1.length; i++) {
            lblKelime.setText(lblKelime.getText()+" "+ekranYaz1[i]);
        }
        puan=puan-100;
        lblSoruPuan.setText(Integer.toString(puan));
        if (puan==0) 
        {
            ekranaYaz();
        }
        
    }//GEN-LAST:event_btnHarfisteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //fonksiyonlara git
        kelimeOku();
        ekranaYaz();
        oyunSure();
    }//GEN-LAST:event_formWindowOpened

    private void textFieldTahminKelimeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldTahminKelimeKeyPressed
        
    }//GEN-LAST:event_textFieldTahminKelimeKeyPressed

    private void lblTimeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblTimeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTimeKeyPressed

    private void btnOyunuBitirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOyunuBitirActionPerformed
        oyunBitti();
    }//GEN-LAST:event_btnOyunuBitirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new PencereOyun().setVisible(true);
                
            }
            
        });
            
    }
     
    String [] diziSoru= new String[14] ;
    String [] diziKelime= new String[14] ;
    
    private void kelimeOku()
    {
    String kelime1="",kelime2;
    int indx=0;
        for (int i = 4; i < 11; i++) {
            
            for (int j = 0; j < 2; j++) {
                
                do {
                    kelime2=kelime1;
                   
                    kelime1 = kelimeHarf(i);
                    if (kelime1.isEmpty()==false) {
                        diziKelime[indx]=kelime1.substring(0,i);
                        diziSoru[indx]=kelime1.substring(i+1);                        
                    }
                } while (kelime1.equals(kelime2)|| kelime1.isEmpty());
                indx++;
            }
            
        }
    
  
    }
    
    private String kelimeHarf(int a)
    {
        BufferedReader oku = null;
        String [] satir = null;
        try {
            oku=new BufferedReader(new FileReader(a+"harfKelime.txt"));
            satir=oku.lines().toArray(String [] :: new);
            oku.close();
        } catch (Exception e) {
        }
        Random satirDondur=new Random();
        return satir[satirDondur.nextInt(satir.length)];
        
    }
    
    int tut = -1;
    char [] harf = null;
    int puan;
    private void ekranaYaz()//soru ve cevabı ekrana yazan ve yeni soruyu görünteleyen fonksiyon
    {
    tut++;
        if (tut>=diziSoru.length) //oyun bittiğinde gel
        {
            oyunBitti();
            return;
        }
        lblSoru.setText(diziSoru[tut]);
       
        harf=diziKelime[tut].toCharArray();
        ekranYaz1=diziKelime[tut].toCharArray();
        puan=harf.length*100;
        lblKelime.setText("");
        for (int i = 0; i < harf.length; i++) {
            lblKelime.setText(lblKelime.getText()+"_ ");
            ekranYaz1[i]='_';
        }
        lblSoruPuan.setText(Integer.toString(puan));
               
    }
    int sayac = 240;//4 dk
    private void oyunSure()
    {
        Timer myTimer=new Timer();
             TimerTask gorev =new TimerTask() {
 
                    @Override
                    public void run() {
                        if(sayac == 0){
                                myTimer.cancel();
                                oyunBitti();
                        }
                        else{
                            sayac--;
                            lblTime.setText(sayac/60 + ":" + sayac%60);                            
                        }
                    }
             }; 
             myTimer.schedule(gorev,0,1000);       
    }
    
    private void oyunBitti()
    {
        this.setVisible(false);
        Date tarih=new Date();
        JOptionPane.showMessageDialog(null,"kalan süreniz: "+sayac/60 + ":" + sayac%60+"\ntoplanan puan: "+toplamPuan+"\ntarih: "+tarih);
    }
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGonder;
    private javax.swing.JButton btnHarfiste;
    private javax.swing.JButton btnOyunuBitir;
    private javax.swing.JButton btnSil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblKelime;
    private javax.swing.JLabel lblSoru;
    private javax.swing.JLabel lblSoruPuan;
    private javax.swing.JLabel lblTahminKelimeGoster;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblToplamPuan;
    private javax.swing.JPanel pnlSoru;
    private javax.swing.JPanel pnlSoruPuan;
    private javax.swing.JPanel pnlSurePuan;
    private javax.swing.JPanel pnlTahminEt;
    private javax.swing.JTextField textFieldTahminKelime;
    // End of variables declaration//GEN-END:variables
}
